services:
  es:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - foodtrucks-db
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  
  
  flask-app:
    build:
      context: .
    depends_on:
      es:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=es   
    networks:
      - foodtrucks-db
      - foodtrucks-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  
  
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
      - ./templates/index.html:/usr/share/nginx/html/index.html
    depends_on:
      flask-app:
        condition: service_healthy
    networks:
      - foodtrucks-net

networks:
  foodtrucks-db:
    driver: bridge
  foodtrucks-net:
    driver: bridge

volumes:
  es_data:
    driver: local
